### ISSUE TITLE
Use regular-case commands with subcommands

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/ProtectionAreas#3]
Rewrite commands to use "/protection add" format rather than "/ProtAdd". The new one is easier to document in the Info.lua file and it is easier to change if the top-level command interferes with another plugin.

It is assumed that we will have a "CommandAlias" plugin that will allow players to define their own aliases for commands, so the players will be able to, at their own discretion, create the ProtAdd etc. aliases.

**Comment by williamhatcher** [comment]
This issue should be closed. I believe these were changed over in commit 9edfee93048f214175cbed7eb2a3f77f7ac4abb2
